
package com.xm.webservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ZHB_SEND_RESULT2", targetNamespace = "urn:sap-com:document:sap:rfc:functions")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZHBSENDRESULT2 {
    /**
     * 
     * @param iGJAHR
     * @param iMONAT
     * @param etPROFITREP
     * @param etSRCBREP
     */
    @WebMethod(operationName = "ZHB_SEND_RESULT2", action = "urn:sap-com:document:sap:rfc:functions:ZHB_SEND_RESULT2:ZHB_SEND_RESULT2Request")
    @RequestWrapper(localName = "ZHB_SEND_RESULT2", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "com.xm.webservice.client.ZHBSENDRESULT2_Type")
    @ResponseWrapper(localName = "ZHB_SEND_RESULT2Response", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "com.xm.webservice.client.ZHBSENDRESULT2Response")
    public void zhbSENDRESULT2(
        @WebParam(name = "I_GJAHR", targetNamespace = "")
        String iGJAHR,
        @WebParam(name = "I_MONAT", targetNamespace = "")
        String iMONAT,
        @WebParam(name = "ET_PROFIT_REP", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ZHBTPROFIT> etPROFITREP,
        @WebParam(name = "ET_SRCB_REP", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ZHBTSRCB> etSRCBREP);

}
