
package com.xm.webservice.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ZHB_SEND_RESULT2", targetNamespace = "urn:sap-com:document:sap:rfc:functions", wsdlLocation = "http://10.80.40.23:8000/sap/bc/srt/wsdl/flv_10002A111AD1/bndg_url/sap/bc/srt/rfc/sap/zhb_send_result2/800/zhb_send_result2/zhb_send_result2?sap-client=800")
public class ZHBSENDRESULT2_Service
    extends Service
{

    private final static URL ZHBSENDRESULT2_WSDL_LOCATION;
    private final static WebServiceException ZHBSENDRESULT2_EXCEPTION;
    private final static QName ZHBSENDRESULT2_QNAME = new QName("urn:sap-com:document:sap:rfc:functions", "ZHB_SEND_RESULT2");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.80.40.23:8000/sap/bc/srt/wsdl/flv_10002A111AD1/bndg_url/sap/bc/srt/rfc/sap/zhb_send_result2/800/zhb_send_result2/zhb_send_result2?sap-client=800");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZHBSENDRESULT2_WSDL_LOCATION = url;
        ZHBSENDRESULT2_EXCEPTION = e;
    }

    public ZHBSENDRESULT2_Service() {
        super(__getWsdlLocation(), ZHBSENDRESULT2_QNAME);
    }

    public ZHBSENDRESULT2_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZHBSENDRESULT2_QNAME, features);
    }

    public ZHBSENDRESULT2_Service(URL wsdlLocation) {
        super(wsdlLocation, ZHBSENDRESULT2_QNAME);
    }

    public ZHBSENDRESULT2_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZHBSENDRESULT2_QNAME, features);
    }

    public ZHBSENDRESULT2_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZHBSENDRESULT2_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZHBSENDRESULT2
     */
    @WebEndpoint(name = "ZHB_SEND_RESULT2")
    public ZHBSENDRESULT2 getZHBSENDRESULT2() {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "ZHB_SEND_RESULT2"), ZHBSENDRESULT2.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZHBSENDRESULT2
     */
    @WebEndpoint(name = "ZHB_SEND_RESULT2")
    public ZHBSENDRESULT2 getZHBSENDRESULT2(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "ZHB_SEND_RESULT2"), ZHBSENDRESULT2.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZHBSENDRESULT2_EXCEPTION!= null) {
            throw ZHBSENDRESULT2_EXCEPTION;
        }
        return ZHBSENDRESULT2_WSDL_LOCATION;
    }

}
